Fixed these Splunk 6 test failures by updating tests
+ EntityTest::testRefreshEntityInCustomNamespace

Splunk_NoSuchEntityException: No entity exists with name 'getstarted'./var/www/html/splunk-splunk-sdk-php-01c60b6-5.3.28-localhost/Splunk/Collection.php:186/var/www/html/splunk-splunk-sdk-php-01c60b6-5.3.28-localhost/tests/EntityTest.php:277

CAUSE: The gettingstarted app is disabled in Splunk 6
FIX: Use the search app instead of the getting started app
SEE: Change to EntityTest.php

+ ReceiverTest::testSubmitMultipleEvents

Timed out waiting for events to be indexed. Expected 3. Got 1./var/www/html/splunk-splunk-sdk-php-01c60b6-5.3.28-localhost/tests/ReceiverTest.php:145/var/www/html/splunk-splunk-sdk-php-01c60b6-5.3.28-localhost/tests/ReceiverTest.php:91/var/www/html/splunk-splunk-sdk-php-01c60b6-5.3.28-localhost/tests/ReceiverTest.php:35

CAUSE: 10 seconds is not always enough time for index to be built
FIX: Increase wait time to 30 seconds
SEE: Change to ReceiverTest.php

+ ReceiverTest::testAttachAndSendMultipleEvents

Timed out waiting for events to be indexed. Expected 3. Got 1./var/www/html/splunk-splunk-sdk-php-01c60b6-5.3.28-localhost/tests/ReceiverTest.php:145/var/www/html/splunk-splunk-sdk-php-01c60b6-5.3.28-localhost/tests/ReceiverTest.php:108/var/www/html/splunk-splunk-sdk-php-01c60b6-5.3.28-localhost/tests/ReceiverTest.php:51

CAUSE: 10 seconds is not always enough time for index to be built
FIX: Increase wait time to 30 seconds
SEE: Change to ReceiverTest.php
Signed-off-by: David Noble <dnoble@splunk.com>